# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 17:24
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
