# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20160504_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, default='/files/assets/images/placeholder.jpg', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.Categories'),
        ),
    ]
