# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 15:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import filebrowser.fields
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20160505_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('cover', filebrowser.fields.FileBrowseField(default='/files/assets/images/placeholder.jpg', max_length=200, verbose_name='Image')),
                ('auto_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='test_app.Category2')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='cover',
            field=filebrowser.fields.FileBrowseField(default='/files/assets/images/placeholder.jpg', max_length=200, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.Categories'),
        ),
    ]
