# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_category2_cover2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category2',
            name='cover2',
        ),
    ]
