# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_remove_category2_cover2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(default='/files/assets/images/placeholder.jpg', max_length=200, verbose_name='Image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Category2')),
            ],
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
    ]
